import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background:                  '#fbf9f4',
        primary:                     '#49624a',
        secondary:                   '#94492c',
        'on-primary':                '#ffffff',
        'on-secondary':              '#ffffff',
        'on-background':             '#1b1c19',
        'on-surface':                '#1b1c19',
        surface:                     '#fbf9f4',
        'surface-bright':            '#fbf9f4',
        'surface-dim':               '#dbdad5',
        'surface-container':         '#f0eee9',
        'surface-container-low':     '#f5f3ee',
        'surface-container-high':    '#eae8e3',
        'surface-container-highest': '#e4e2dd',
        'surface-container-lowest':  '#ffffff',
        'surface-variant':           '#e4e2dd',
        'on-surface-variant':        '#434841',
        outline:                     '#737971',
        'outline-variant':           '#c3c8bf',
        'primary-fixed':             '#ceeacb',
        'primary-fixed-dim':         '#b2ceb0',
        'primary-container':         '#627b61',
        'on-primary-fixed':          '#09200d',
        'on-primary-fixed-variant':  '#354c35',
        'on-primary-container':      '#f7fff2',
        'secondary-container':       '#fe9d7a',
        'secondary-fixed':           '#ffdbcf',
        'secondary-fixed-dim':       '#ffb59b',
        'on-secondary-fixed':        '#380d00',
        'on-secondary-container':    '#773318',
        tertiary:                    '#775610',
        'tertiary-container':        '#936f28',
        'tertiary-fixed':            '#ffdea8',
        'tertiary-fixed-dim':        '#ecc071',
        'on-tertiary':               '#ffffff',
        'on-tertiary-fixed':         '#271900',
        'on-tertiary-container':     '#fffbff',
        'inverse-surface':           '#30312e',
        'inverse-on-surface':        '#f2f1ec',
        'inverse-primary':           '#b2ceb0',
        error:                       '#ba1a1a',
        'on-error':                  '#ffffff',
        'error-container':           '#ffdad6',
        'on-error-container':        '#93000a',
        'surface-tint':              '#4c644c',
      },
      fontFamily: {
        headline: ['Newsreader', 'Georgia', 'serif'],
        body:     ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        label:    ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      boxShadow: {
        editorial: '0 20px 40px rgba(27, 28, 25, 0.06)',
        nav: '0 -20px 40px rgba(27, 28, 25, 0.06)',
      },
    },
  },
  plugins: [],
} satisfies Config
